name: Our Jobs
on: push
jobs:
  hello1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, GitHub Actions!" > hello.txt
  hello2:
    runs-on: ubuntu-latest
    steps:
      - run: cat hello.txt
