name: Our Jobs
on: push
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Hello!'
  echo_if:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    steps:
      - run: echo 'Hello, main!'
  job3:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'skip ci')
    steps:
      - run: echo 'Hello, Skip CI'
