name: Our Jobs
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: echo "word=GitHub" >> $GITHUB_OUTPUT
      - id: step2
        run: echo "word=Actions" >> $GITHUB_OUTPUT
    outputs:
      word1: ${{ steps.step1.outputs.word }}
      word2: ${{ steps.step2.outputs.word }}
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.job }}
      - run: echo ${{ needs.job1.outputs.word1 }}
      - run: echo ${{ needs.job1.outputs.word2 }}
  job3:
    needs: [job1, job2]
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.job }}
